### ISSUE TITLE
[Feature Request] GBK encoding

### ISSUE THREAD

**Issue by laqieer** [FEBuilderGBA/FEBuilderGBA#11]
![image](https://user-images.githubusercontent.com/8841957/61187031-1ee75a00-a69f-11e9-96ef-c2aef4f2f987.png)
For double byte encoding text in Chinese ROM, if both of the two bytes are in [0xA1, 0xFE], decode it as GBK encoding.
ZH_TBL doesn't use that range, so no conflict.
[source code only for reference](https://github.com/laqieer/FE7CNLOL/blob/master/src/showFont.c#L271), you needn't read it for this feature request.

**Comment by FEBuilderGBA** [comment]
This version is not a widely used version and is not supported.
As it does not correspond to the European version of FE7E, FE8E,
it is unrealistic to correspond to all versions, because it takes a lot of time and effort.

I made a UTF-8 patch for FE7U and FE8U.
I think that UTF-8 should be used rather than GBK936.

For FE7J and FE8J, the default is SJIS and can not be changed.
I think that it should be converted to UTF-8.

It is more versatile to support UTF-8 than to support local character code.
